apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Namespace","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"ingress-nginx","app.kubernetes.io/name":"ingress-nginx"},"name":"ingress-nginx"}}
  creationTimestamp: "2025-06-07T02:36:36Z"
  labels:
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
    kubernetes.io/metadata.name: ingress-nginx
  name: ingress-nginx
  resourceVersion: "12908"
  uid: c5f4895f-6930-4c8b-a2aa-4619cdb6ed3a
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
