name: fraud-tf-cpu
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - azure-cli
  - pip:
      - numpy
      - pandas
      - scikit-learn
      - uvicorn
      - azure-ai-ml
      - azure-identity