$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
code: ../src
command: >-
  python src/train.py --train-data ${{inputs.train_data}} --output-dir ${{outputs.model_dir}} || echo "Training job failed due to encoding issues."
inputs:
  train_data:
    type: uri_file
    path: azureml:cleaned_train:2
outputs:
  model_dir:
    type: uri_folder
compute: azureml:mycpucluster
environment:
  conda_file: conda.yaml
  image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:latest