command: >-
  python train.py --train-data ${{inputs.train_data}} --output-dir ${{outputs.model_dir}}
inputs:
  train_data:
    type: uri_file
    path: azureml:cleaned_train@latest
outputs:
  model_dir:
    type: uri_folder
compute: azureml:mycpucluster
environment:
  name: fraud-tf-cpu
  version: 1