apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-detector-deployment
  labels:
    app: fraud-detector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fraud-detector
  template:
    metadata:
      labels:
        app: fraud-detector
    spec:
      containers:
        - name: fraud-detector
          image: fraudacr12345.azurecr.io/fraud-detector:autoencoder
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
      imagePullSecrets:
        - name: acr-secret
