apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fraud-backend
  template:
    metadata:
      labels:
        app: fraud-backend
    spec:
      containers:
        - name: fraud-detector   # must match CONTAINER_NAME in workflow
          image: fraudacr12345.azurecr.io/fraud-detector:autoencoder
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: MODELS_DIR
              value: /app/models
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"