apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fraud-detector-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /predict
            pathType: Prefix
            backend:
              service:
                name: fraud-detector-service  # FastAPI backend
                port:
                  number: 80
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: frontend-nginx          # Static HTML service
                port:
                  number: 80
