apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fraud-ingress
spec:
  rules:
    - http:
        paths:
          - path: /predict
            pathType: Prefix
            backend:
              service:
                name: fraud-backend
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80