apiVersion: v1
kind: Service
metadata:
  name: fraud-detector-service
spec:
  type: LoadBalancer
  selector:
    app: fraud-detector
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
