# .github/workflows/ci-cd.yml

name: Build_and_Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}  # GitHub secret with JSON output of `az ad sp create-for-rbac --sdk-auth`

      - name: Azure CLI: get ACR login server
        id: acrinfo
        run: |
          ACR_NAME=fraudACR12345
          echo "ACR_LOGIN_SERVER=$(az acr show -n $ACR_NAME --query loginServer -o tsv)" >> $GITHUB_OUTPUT

      - name: Log in to ACR (Docker)
        run: |
          echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ steps.acrinfo.outputs.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Build and push Docker image
        run: |
          IMAGE_TAG=${{ steps.acrinfo.outputs.ACR_LOGIN_SERVER }}/fraud-detector:latest
          docker build -f deployment/Dockerfile -t $IMAGE_TAG .
          docker push $IMAGE_TAG

  deploy-to-aks:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure CLI: AKS creds
        uses: azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          resource-group: fraud-rg
          cluster-name: fraudAKSCluster

      - name: Update Kubernetes Deployment image
        run: |
          kubectl set image deployment/fraud-detector-deployment \
            fraud-detector=${{ steps.acrinfo.outputs.ACR_LOGIN_SERVER }}/fraud-detector:latest \
            --namespace default
